### ISSUE TITLE
upstreams should be able to be in multiple locations

### ISSUE THREAD

**Issue by geneoshaughnessy** [Kroger-Technology/Snow-Globe#9]

**Comment by STeveShary** [comment]
Upstreams can be in multiple files.   Our recommendation is that you include them from one file.  Then you can set the file that Snow-Globe should generate to be the one file.  The example below would be:

**upstreams.conf**
```
include route1Upstreams.conf;
include route2Upstreams.conf;
include route3Upstreams.conf;
// ...
include route1Upstreams.conf;
```

Then in the `snow-globe.yml` file you would have the setting:
`upstream.file.path: "/etc/nginx/upstreams.conf"`

Snow-Globe is going to read your configuration, build a temporary file that contains all of your upstreams.  The `upstreams.file.path` tells Snow-Globe where to inject that file.
